spring.application.name=StudentsManagementSystem
# BD
spring.datasource.url=jdbc:postgresql://localhost:5432/aadinath
spring.datasource.username=postgres
# 123 pc trabajo y 3483 pc personal
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion para hibernar
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show_sql=true

# Puerto
server.port=8081